GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "chickens",
  "author": "silky chickens",
  "url": "https://google.com/chickens",
  "likes": 110
}

###
POST http://localhost:3003/api/users
content-type: application/json

{
  "name": "marcus",
  "username": "Marcus Rashford",
  "password": "2424536"
}